### ISSUE TITLE
Validate vector JSON schema

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/yaml-yugi-limit-regulation#6]
1. Create `src/vector.schema.{yaml or json}`, a JSON schema for the `*.vector.json` files in `data/`, like https://github.com/DawnbrandBots/yaml-yugi/blob/master/src/assignments/schema.yaml.
1. Create a script in `src/` that validates all such files against the created schema, like https://github.com/DawnbrandBots/yaml-yugi/blob/master/src/assignments/validate.py. This should be Unix-y, so exit code zero and no output if successful, and nonzero exit code with noisy output indicating the problematic file(s) otherwise.
1. Have GitHub Actions automatically run this validation script as appropriate, like https://github.com/DawnbrandBots/yaml-yugi/blob/master/.github/workflows/validate-assignments.yaml

**Comment by kevinlul** [comment]
```
title: YAML Yugi limit regulation vectors
description: Yu-Gi-Oh! limit regulations, stored as a mapping from Konami ID to the number allowed per deck
```
```
date: when this limit regulation became effective
regulation: the effective regulations, as a mapping from Konami ID to the number allowed per deck
```

**Comment by xyj-3** [comment]
I'm giving you the license on the files.
